### ISSUE TITLE
Scp error: Error: Timed out while waiting for handshake

### ISSUE THREAD

**Issue by select** [spmjs/node-scp2#107]
How would I increase the timeout time, the server on the other side is very slow and I have not control over it.

**Comment by danielecr** [comment]
as specified in the section https://github.com/spmjs/node-scp2#methods
"more on these values at" here:
https://github.com/mscdex/ssh2#client-methods

the option name is

readyTimeout, default to 20000
I suggest to use also

> debug: console.log

**Comment by select** [comment]
thanks
