### ISSUE TITLE
copying big file fails

### ISSUE THREAD

**Issue by cherchyk** [spmjs/node-scp2#76]
I'm downloading a 25mb zip file from sftp.  Zip has one csv file in UTF.

scp2 downloads 25.8 MB (27,103,241 bytes) instead of 25.8 MB (27,103,654 bytes).

tried couple of times locally and remote.  Any suggestions why this is happen?

**Comment by markpoon-moneris** [comment]
when you do this with scp from the command line does it fail on trying to transfer a large file? is the destination server an ibm server?

**Comment by cherchyk** [comment]
scp2 depends on ssh2 which depends on ssh2-streams where were a bug
 please update ssh2 in order to get ssh2-streams  v0.1.16

scp2 was failing on files over 25mg
